---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: Flag-Health

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 0
    from: 2026-03-27T06:49:00Z
  - percentage: 100
    from: 2026-03-27T06:54:00Z

conditions: []
