---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: Flag-Health

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - not:
          allOf:
            - group:
                name: developers
    flagValue: false
