---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: developers

description: 

conditions:
  allOf:
    - property:
        name: userId
        operator: in-array
        operands:
            - 2134324dffw3213
